require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# Workaround to avoid Xcode caching of Pods
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Securely compiles and hooks the native controllers for Google and Apple auth
  capacitor_pods
end