platform :ios, '13.0'
use_frameworks!

# Workaround to avoid Xcode caching of Pods
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Left empty deliberately because SPM handles plugin linkage 
end