platform :ios, '13.0'
use_frameworks!

# Workaround to avoid Xcode caching of Pods
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Bypassing the undefined function call since native modules are loaded securely via SPM instead
end